project:
  type: website
  output-dir: docs

website:
  title: "Eugenio Turchet"
  description: "PhD student in Mathematics at GSSI working on numerical linear algebra, matrix nearness problems, and randomized algorithms."
  favicon: images/logo.png

  navbar:
    logo: images/logo.png
    background: white
    foreground: black
    search: false

    right:
      - text: HOME
        href: index.qmd

      - text: PUBLICATIONS
        href: publications.qmd

      - text: THESIS
        href: thesis.qmd

      - text: CODES
        href: codes.qmd

      - text: CV
        href: cv.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    include-in-header:
      text:
        <meta name="google-site-verification" content="pIF2IzTFBIvKPEbiCSZlzwqV0IYP6NMuor4Ls4qbIk4" />


